### ISSUE TITLE
Always returning error? Solved

### ISSUE THREAD

**Issue by wattzor** [stefanbesler/Twinson#4]
Hello, thank you for an awesome tool. 

i just have a smal issue it seams like it parses the json perfectly. But i always (Even in the example you provided) get the error flag that is high.

it seams like like it the  _jsonPtr^ is always "88" or X when this happens.

Do you know why this happens, or what i can change to get a "Success" flag if it processes the whole string?

EDIT: this just seams to happen if you post the Json-string directly in the function, if you passa variable it works better.

**Comment by wattzor** [comment]
This just seams to happen if you post the Json-string directly in the function, if you pass variable it works better.

**Comment by stefanbesler** [comment]
Hm, thanks for the info, will try to fix it by copying the string initiallyAm 27.07.2024 um 15:10 schrieb wattzor ***@***.***>:﻿
This just seams to happen if you post the Json-string directly in the function, if you pass variable it works better.
